import "./globals.css";
import { Kumbh_Sans } from "next/font/google";
import { Providers } from "./GlobalRedux/provider";

const kumbh_sans = Kumbh_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "E-Commerce Product Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={kumbh_sans.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
